config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "home#index"

  resources :books, only: [:show, :index], param: :slug do
    resources :pages, only: :show, param: :number, format: true
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :pages, class_name: "BookPage"

  before_validation :build_slug

  validates :title, :authors, :slug, presence: true
  validates :slug, uniqueness: true, on: :save

  scope :latest_books, -> { order("created_at DESC").limit(3) }

  scope :ordered_by_title, -> { order("title ASC") }

  private

  def build_slug
    slug = title.to_s.parameterize
    possible_slug = slug
    suffix = 2
    until self.class.find_by(slug: possible_slug).nil?
      possible_slug = "#{slug}-#{suffix}"
      suffix += 1
    end
    self.slug = possible_slug
  end
end

app/models/book_page.rb
class BookPage < ApplicationRecord
  belongs_to :book

  validates :content, presence: true
  validates :number, numericality: true
  validates_uniqueness_of :number, scope: [:book_id]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.ordered_by_title
  end

  def show
    book = Book.find_by!(slug: params[:slug])

    redirect_to book_page_path(book_slug: book.slug, number: 1, format: :html)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @latest_books = Book.latest_books
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    @book = Book.find_by!(slug: params[:book_slug])
    @page = @book.pages.find_by!(number: params[:number])

    @total_pages = @book.pages.count

    respond_to(:html, :text)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
  def display_authors(authors)
    case authors.size
    when 0
      "(unknown author)"
    when 1
      "by #{authors.first}"
    when 2
      "by #{authors.first} and #{authors.last}"
    else
      "by #{authors[0...-1].join(", ")} and #{authors.last}"
    end
  end
end

app/views/books/index.html.erb
<section>
  <header>
    <h2>All books listing</h2>
    <p>See all our catalog.</p>
  </header>
  <ul class="listing">
    <% @books.each do |book| %>
      <li>
        <h3><%= link_to book.title, book_path(book.slug) %></h3>
        <p class="latest__details">
          <%= display_authors(book.authors) %>
        </p>
      </li>
  <% end %>
  </ul>
</section>

app/views/home/index.html.erb
<section>
  <header>
    <h2>Latest books</h2>
    <p>
      <%= @latest_books.empty? ? "Sorry, we don't have any books right now." : "See the latest books added to our catalog." %>
    </p>
  
  </header>
  <% @latest_books.each do |book| %>
    <aside class="latest">
      <h3><%= book.title %></h3>
      <p class="latest__details">
        <%= display_authors(book.authors) %>
      </p>
      <p class="latest__cta">
        <%= link_to("Read it now →", book_path(book.slug)) %>
      </p>
    </aside>
  <% end %>

</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OpenBooks</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <nav>
        <a href="/" class="title">OpenBooks</a>
        <ul>
          <li><%= link_to_unless_current("All Books", books_path) %></li>
        </ul>
      </nav>
    </header>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/show.html.erb
<section class="book-page">
  <section class="book-page__top">
    <span class="book-page__title"><%= @book.title %></span>
  </section>
  <section class="book-page__content">
    <%= simple_format(@page.content) %>
  </section>
  <section class="book-page__bottom">
    <div class="book-page__previous">
      <%= previous_page(@book, @page.number, @total_pages) %>
    </div>
    <div class="book-page__number">
      <%= @page.number %>
    </div>
    <div class="book-page__next">
      <%= next_page(@book, @page.number, @total_pages) %>
    </div>
  </section>
</section>

app/views/pages/show.text.erb
<%= @book.title %>
<%= "-"*80 %>

<%= @page.content %>

<%= "-"*80 %>
page <%= @page.number %> of <%= @total_pages %>